Repository liam-mack/Balls-of-War, pull requests merged in 2020-10, with the labels that each got.

#1 Added sequelize, player schema and lakers data
  .env
  .eslintignore
  .eslintrc.json
  .gitignore
  Players.xlsx
  config/config.js
  models/index.js
  models/player.js
  package-lock.json
  package.json
  routes/html-routes.js
  server.js
  sql/schema.sql
  src/index.js
Labels: enhancement

#8 Altered travis.yml to refer to 'main'
  .travis.yml
Labels: good first issue

#13 Skeleton1
  .eslintignore
  .eslintrc.json
  .gitignore
  .travis.yml
  README.md
  React README.md
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/registerServiceWorker.js
  package-lock.json
  package.json
  routes/html-routes.js
  server.js
  sql/schema.sql
  src/App.js
  testfile
Labels: bug

#16 Airbnb lint w/ Travis
  package-lock.json
  package.json
Labels: documentation

#17 Added some npm packages
  .env
  .gitignore
  Players.xlsx
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/registerServiceWorker.js
  package-lock.json
  package.json
  routes/html-routes.js
  server.js
  sql/schema.sql
Labels: good first issue

#18 Asset update
  Players.xlsx
  README.md
  assets/Proposal/1-Login/Desktop HD.png
  assets/Proposal/1-Login/Desktop.png
  assets/Proposal/1-Login/Mobile Portrait.png
  assets/Proposal/1-Login/Tablet Portrait.png
  assets/Proposal/2-Deck Select/Desktop HD.png
  assets/Proposal/2-Deck Select/Desktop.png
  assets/Proposal/2-Deck Select/Mobile Portrait.png
  assets/Proposal/2-Deck Select/Tablet Portrait.png
  assets/Proposal/3-Game Page/Desktop HD.png
  assets/Proposal/3-Game Page/Desktop.png
  assets/Proposal/3-Game Page/Mobile Portrait.png
  assets/Proposal/3-Game Page/Tablet Portrait.png
  assets/images/placeholder.png
  client/public/index.html
  client/src/App.js
  client/src/components/lakers.js
  client/src/utils/API.js
  models/lakers.js
  models/player.js
  package-lock.json
  package.json
  routes/api-routes.js
  server.js
Labels: enhancement

#25 Added sample game page
  client/src/App.css
  client/src/App.js
  client/src/components/deck/deck.js
  client/src/components/gamePage/page.js
  client/src/components/gamePage/placeholder.js
  client/src/components/gamePage/playerCard.js
  client/src/components/loginPage/inputField.js
  client/src/components/loginPage/login.js
  client/src/index.js
  package-lock.json
  package.json
Labels: enhancement

#26 console log player values
  client/src/components/gamePage/page.js
  client/src/components/gamePage/playerCard.js
Labels: enhancement

#27 Sqluuid
  client/src/components/lakers.js
  client/src/utils/API.js
  models/lakers.js
  package-lock.json
  package.json
  routes/api-routes.js
  routes/html-routes.js
  server.js
  sql/seedBomb.js
  sql/seeds/seedHeat.js
  sql/seeds/seedLakers.js
Labels: enhancement

#30 Added stats for 4 base teams
  Players.xlsx
Labels: documentation

#31 Updated table syntax for Raptors/Heat
  Players.xlsx
Labels: documentation

#33 Added eslint config and edited files
  .eslintignore
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/gamePage/page.js
  client/src/components/gamePage/placeholder.js
  client/src/components/gamePage/playerCard.js
  client/src/components/lakers.js
  client/src/components/loginPage/inputField.js
  client/src/components/loginPage/login.js
  client/src/index.js
  client/src/utils/API.js
  config/config.js
  models/heat.js
  models/lakers.js
  models/raptors.js
  models/rockets.js
  package-lock.json
  package.json
  routes/api-routes.js
  server.js
  sql/seedBomb.js
Labels: bug

#39 Added select page and react router
  .eslintrc.json
  client/package-lock.json
  client/src/App.js
  client/src/index.js
  client/src/pages/Selection.js
  package-lock.json
  routes/api-routes.js
Labels: enhancement

#42 deck selection sends state to game page
  client/src/App.js
  client/src/pages/Play.js
  client/src/pages/Selection.js
  client/src/utils/API.js
  client/src/utils/SessionStore.js
Labels: enhancement
