Repository liam-mack/Balls-of-War, pull requests merged in 2020-11, with the labels that each got.

#44 Passport
  client/src/App.js
  client/src/pages/Home.js
  client/src/pages/Play.js
  config/middleware/isAuthenticated.js
  config/passport.js
  models/user.js
  package-lock.json
  package.json
  routes/api-routes.js
  server.js
Labels: enhancement

#45 Updated the selection page
  client/src/App.css
  client/src/App.js
  client/src/components/deck/deck.js
  client/src/components/gamePage/playerCard.js
  client/src/components/lakers.js
  client/src/components/loginPage/inputField.js
  client/src/components/loginPage/login.js
  client/src/index.js
  client/src/pages/Selection.js
  client/src/utils/API.js
  client/src/utils/SessionStore.js
  package-lock.json
  package.json
  server.js
  sql/seedBomb.js
Labels: enhancement

#47 Sets game state and loads player teams and decks
  .eslintrc.json
  client/package-lock.json
  client/src/components/GameHand.js
  client/src/components/Testing.js
  client/src/pages/Play.js
  client/src/utils/API.js
  package-lock.json
  package.json
  routes/api-routes.js
Labels: enhancement

#52 gamestate renders with teams and decks
  client/src/App.js
  client/src/components/GameHand.js
  client/src/components/Play/Deck.js
  client/src/components/Play/deck.css
  client/src/components/Play/grave.js
  client/src/components/Play/graveyard.css
  client/src/components/Play/page.js
  client/src/components/Play/playerCard.js
  client/src/pages/Home.js
  client/src/pages/Play.js
  client/src/pages/Selection/Selection.js
  client/src/utils/API.js
  client/src/utils/Actions.js
  config/middleware/isAuthenticated.js
  models/game.js
  models/index.js
  models/user.js
  package-lock.json
  package.json
  routes/api-routes.js
  server.js
Labels: enhancement

#55 Branch conflict
  client/src/pages/Play.js
Labels: bug

#56 Refactored deck click and stat click
  .eslintrc.json
  client/src/components/Play/Card.js
  client/src/components/Play/Deck.js
  client/src/pages/Play.js
  client/src/utils/API.js
  models/game.js
  routes/api-routes.js
Labels: enhancement

#58 Altered Card component and added Sass styling
  client/src/components/Play/Card.js
  client/src/components/Play/card.scss
Labels: enhancement

#60 Fixed selection button to play page
  assets/SessionStore.js
  assets/deck/deck.js
  assets/gamePage/placeholder.js
  assets/gamePage/stats.js
  assets/loginPage/inputField.js
  assets/loginPage/login.js
  assets/page.js
  client/src/components/GameHand.js
  client/src/components/Testing.js
  client/src/components/gamePage/placeholder.js
  client/src/pages/Selection/Selection.js
  client/src/pages/Selection/selection.css
  client/src/utils/API.js
  client/src/utils/Actions.js
  package-lock.json
  package.json
  routes/api-routes.js
Labels: enhancement

#65 Gamelogic4
  client/src/components/Play/Card.js
  client/src/components/Play/Deck.js
  client/src/pages/Play.js
  client/src/utils/API.js
  models/game.js
  package.json
  routes/api-routes.js
Labels: bug, enhancement

#67 Added turn switching, stat resolving, grave etc.
  client/package-lock.json
  client/public/index.html
  client/src/App.js
  client/src/components/Play/Deck.js
  client/src/components/Play/Graveyard.js
  client/src/components/Play/grave.js
  client/src/index.js
  client/src/pages/Home/Home.js
  client/src/pages/Opponent.js
  client/src/pages/Play.js
  models/game.js
  package-lock.json
  package.json
  routes/api-routes.js
  server.js
Labels: bug, enhancement

#72 Added stat comparisons for height, turnovers, personalfouls
  .eslintignore
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/index.js
  client/src/pages/Home/Home.js
  client/src/pages/Play.js
  client/src/utils/API.js
  config/config.js
  models/game.js
  models/index.js
  package-lock.json
  package.json
  routes/api-routes.js
  routes/auth.js
  routes/game.js
  routes/helpers.js
  routes/html-routes.js
  scripts/schema.sql
  scripts/seedBomb.js
  scripts/seeds/seedHeat.js
  scripts/seeds/seedLakers.js
  scripts/seeds/seedRaptors.js
  scripts/seeds/seedRockets.js
  server.js
Labels: bug, enhancement

#75 added some passport stuff
  client/src/App.js
  client/src/components/Play/card.scss
  client/src/pages/Home.js
  client/src/pages/Home/Home.js
  client/src/pages/Login.jsx
  client/src/pages/Signup.jsx
  client/src/pages/home.css
  client/src/utils/API.js
  config/middleware/isAuthenticated.js
  routes/auth.js
  server.js
Labels: bug, enhancement, help wanted

#76 Card Component and beginning of Scoreboard
  client/src/components/Play/Scoreboard.js
  client/src/components/Play/card.css
  client/src/components/Play/card.scss
  client/src/components/Play/deck.css
  client/src/images/Card/Images.js
  client/src/pages/Opponent.js
  client/src/pages/Play.js
Labels: enhancement

#77 Game render1
  client/src/components/Play/Card.js
  client/src/components/Play/Scoreboard.js
  client/src/components/Play/card.scss
  client/src/components/Play/deck.css
  client/src/components/Play/graveyard.css
  client/src/components/Play/scoreboard.scss
  client/src/images/graveyard/graveyard.jpg
  client/src/images/graveyard/graveyard.png
  client/src/pages/Opponent.js
  client/src/pages/Play.js
Labels: bug

#78 Added ties for turn decider and started checking for game completion
  client/src/App.js
  routes/game.js
  routes/helpers.js
Labels: bug, enhancement

#79 Added the header component
  client/public/index.html
  client/src/App.js
  client/src/components/HeaderText/header.css
  client/src/components/HeaderText/header.js
  client/src/pages/Login.js
  client/src/pages/Login.jsx
  client/src/pages/Signup.js
  client/src/pages/Signup.jsx
  client/src/pages/home.css
  package-lock.json
Labels: enhancement

#80 Passport3
  client/package-lock.json
  client/src/App.js
  client/src/components/Header.js
  client/src/components/HeaderText/header.css
  client/src/components/HeaderText/header.js
  client/src/components/header.css
  client/src/pages/Login.js
  client/src/pages/Signup.js
  client/src/pages/test.jsx
  client/src/utils/API.js
  config/middleware/isAuthenticated.js
  models/user.js
  package-lock.json
  package.json
  routes/auth.js
  routes/helpers.js
  scripts/seedBomb.js
Labels: enhancement

#81 Fixed logic bugs and developed
  client/src/components/Play/Card.js
  client/src/components/Play/Scoreboard.js
  client/src/components/Play/card.scss
  client/src/components/Play/deck.css
  client/src/components/Play/graveyard.css
  client/src/components/Play/scoreboard.scss
  client/src/digital-7mono.ttf
  client/src/pages/Play.js
Labels: bug, enhancement

#85 Minor styling
  client/src/App.css
  client/src/components/Play/Card.js
  client/src/components/Play/Scoreboard.js
  client/src/components/Play/card.scss
  client/src/components/Play/deck.css
  client/src/components/Play/scoreboard.scss
Labels: enhancement

#86 added user auth
  client/src/App.js
  client/src/components/AppRoutes.js
  client/src/components/Header.js
  client/src/config/routes.js
  client/src/context/actions.js
  client/src/context/context.js
  client/src/context/index.js
  client/src/context/reducer.js
  client/src/pages/Login.js
  client/src/pages/Play.js
  client/src/pages/Selection/Selection.js
  client/src/pages/Signup.js
  client/src/utils/API.js
  config/middleware/isAuthenticated.js
  routes/auth.js
  routes/game.js
  server.js
Labels: bug, enhancement

#90 Added indicator active stat
  client/public/images/Rockets/JamesHarden.png
  client/public/images/Rockets/e183f679-fb2b-482a-af53-be3bbae7356b.png
  client/src/components/Play/Card.js
  client/src/components/Play/card.scss
  client/src/components/Play/deck.css
  client/src/pages/Play.js
Labels: bug, enhancement

#92 Showwinner
  client/public/images/bCourt.png
  client/src/App.css
  client/src/App.js
  client/src/components/Header.js
  client/src/components/Play/Card.js
  client/src/components/Play/card.scss
  client/src/components/Play/deck.css
  client/src/components/Play/graveyard.css
  client/src/components/Play/scoreboard.scss
  client/src/components/header.css
  client/src/images/Card/Rockets/ClintCapela.png
  client/src/pages/Login.js
  client/src/pages/Play.js
  client/src/pages/Selection.js
  client/src/pages/Signup.js
  client/src/pages/home.css
  client/src/pages/play.css
  client/src/pages/selection.css
  routes/game.js
  routes/helpers.js
Labels: bug, enhancement

#98 Add alert and protection for failed login
  client/src/pages/Login.js
  client/src/pages/Signup.js
  config/middleware/isAuthenticated.js
Labels: enhancement
